---
title: "Dengue Data Hub:<br/> A Centralized Repository for Dengue-related Data"
subtitle: ""  
author: 
  - "Thiyanga S. Talagala"
  - "University of Sri Jayewardenepura, Sri Lanka"
date: 'R/Medicine Conference 2023 '
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{css, echo = FALSE}
h1, #TOC>ul>li {
  color: #3f007d;
  font-weight: bold;
}
h2, #TOC>ul>ul>li {
  color:  #006837;
  #font-family:  "Times";
  font-weight: bold;
}
h3, #TOC>ul>ul>li {
  color: #ce1256;
  #font-family:  "Times";
  font-weight: bold;
}
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF",
  title_slide_background_color = "#051454",
  title_slide_text_color = "#ff9124"
)
```


# What is Dengue?

